// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: atom/atom_toll.proto
// Original file comments:
// Copyright 2018 Ministry of Power, Works and Housing. Powered by 
// Nigerian Communications Satellite (NigComSat) Ltd.
//
// Licensed under the Atom License, Version 1.0 (the "License");
// you may not use this file except in compliance with the Atom License.
//
#pragma warning disable 1591
#region Designer generated code

using System;
using System.Threading;
using System.Threading.Tasks;
using grpc = global::Grpc.Core;

namespace Atom {
  /// <summary>
  /// functions implemented and exposed by all toll operators consumed by DASH
  /// </summary>
  public static partial class TollAuditService
  {
    static readonly string __ServiceName = "atom.TollAuditService";

    static readonly grpc::Marshaller<global::Atom.Subscription> __Marshaller_Subscription = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atom.Subscription.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Atom.SubscriptionResponse> __Marshaller_SubscriptionResponse = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atom.SubscriptionResponse.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Atom.TollVehicleInfo> __Marshaller_TollVehicleInfo = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atom.TollVehicleInfo.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Atom.VehicleCount> __Marshaller_VehicleCount = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atom.VehicleCount.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Atom.SearchRange> __Marshaller_SearchRange = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Atom.SearchRange.Parser.ParseFrom);

    static readonly grpc::Method<global::Atom.Subscription, global::Atom.SubscriptionResponse> __Method_Subscribe = new grpc::Method<global::Atom.Subscription, global::Atom.SubscriptionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Subscribe",
        __Marshaller_Subscription,
        __Marshaller_SubscriptionResponse);

    static readonly grpc::Method<global::Atom.Subscription, global::Atom.SubscriptionResponse> __Method_Unsubscribe = new grpc::Method<global::Atom.Subscription, global::Atom.SubscriptionResponse>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Unsubscribe",
        __Marshaller_Subscription,
        __Marshaller_SubscriptionResponse);

    static readonly grpc::Method<global::Atom.Subscription, global::Atom.TollVehicleInfo> __Method_GetLiveStream = new grpc::Method<global::Atom.Subscription, global::Atom.TollVehicleInfo>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetLiveStream",
        __Marshaller_Subscription,
        __Marshaller_TollVehicleInfo);

    static readonly grpc::Method<global::Atom.Subscription, global::Atom.VehicleCount> __Method_GetDailyLiveCount = new grpc::Method<global::Atom.Subscription, global::Atom.VehicleCount>(
        grpc::MethodType.ServerStreaming,
        __ServiceName,
        "GetDailyLiveCount",
        __Marshaller_Subscription,
        __Marshaller_VehicleCount);

    static readonly grpc::Method<global::Atom.SearchRange, global::Atom.VehicleCount> __Method_GetVehicleCount = new grpc::Method<global::Atom.SearchRange, global::Atom.VehicleCount>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVehicleCount",
        __Marshaller_SearchRange,
        __Marshaller_VehicleCount);

    static readonly grpc::Method<global::Atom.SearchRange, global::Atom.TollVehicleInfo> __Method_GetVehicleCountSummary = new grpc::Method<global::Atom.SearchRange, global::Atom.TollVehicleInfo>(
        grpc::MethodType.Unary,
        __ServiceName,
        "GetVehicleCountSummary",
        __Marshaller_SearchRange,
        __Marshaller_TollVehicleInfo);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Atom.AtomTollReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of TollAuditService</summary>
    public abstract partial class TollAuditServiceBase
    {
      /// <summary>
      /// subscribe to toll events
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Atom.SubscriptionResponse> Subscribe(global::Atom.Subscription request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// unsubscribe from toll events
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Atom.SubscriptionResponse> Unsubscribe(global::Atom.Subscription request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// get real-time data; process incoming one at a time
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GetLiveStream(global::Atom.Subscription request, grpc::IServerStreamWriter<global::Atom.TollVehicleInfo> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// function implemented and exposed by the toll operators and CR-Chips
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="responseStream">Used for sending responses back to the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>A task indicating completion of the handler.</returns>
      public virtual global::System.Threading.Tasks.Task GetDailyLiveCount(global::Atom.Subscription request, grpc::IServerStreamWriter<global::Atom.VehicleCount> responseStream, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      /// <summary>
      /// get historical data
      /// </summary>
      /// <param name="request">The request received from the client.</param>
      /// <param name="context">The context of the server-side call handler being invoked.</param>
      /// <returns>The response to send back to the client (wrapped by a task).</returns>
      public virtual global::System.Threading.Tasks.Task<global::Atom.VehicleCount> GetVehicleCount(global::Atom.SearchRange request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

      public virtual global::System.Threading.Tasks.Task<global::Atom.TollVehicleInfo> GetVehicleCountSummary(global::Atom.SearchRange request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for TollAuditService</summary>
    public partial class TollAuditServiceClient : grpc::ClientBase<TollAuditServiceClient>
    {
      /// <summary>Creates a new client for TollAuditService</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public TollAuditServiceClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for TollAuditService that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public TollAuditServiceClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected TollAuditServiceClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected TollAuditServiceClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      /// <summary>
      /// subscribe to toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.SubscriptionResponse Subscribe(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Subscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// subscribe to toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.SubscriptionResponse Subscribe(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Subscribe, null, options, request);
      }
      /// <summary>
      /// subscribe to toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.SubscriptionResponse> SubscribeAsync(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return SubscribeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// subscribe to toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.SubscriptionResponse> SubscribeAsync(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Subscribe, null, options, request);
      }
      /// <summary>
      /// unsubscribe from toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.SubscriptionResponse Unsubscribe(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return Unsubscribe(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// unsubscribe from toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.SubscriptionResponse Unsubscribe(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      /// <summary>
      /// unsubscribe from toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.SubscriptionResponse> UnsubscribeAsync(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return UnsubscribeAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// unsubscribe from toll events
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.SubscriptionResponse> UnsubscribeAsync(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Unsubscribe, null, options, request);
      }
      /// <summary>
      /// get real-time data; process incoming one at a time
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Atom.TollVehicleInfo> GetLiveStream(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetLiveStream(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// get real-time data; process incoming one at a time
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Atom.TollVehicleInfo> GetLiveStream(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetLiveStream, null, options, request);
      }
      /// <summary>
      /// function implemented and exposed by the toll operators and CR-Chips
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Atom.VehicleCount> GetDailyLiveCount(global::Atom.Subscription request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetDailyLiveCount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// function implemented and exposed by the toll operators and CR-Chips
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncServerStreamingCall<global::Atom.VehicleCount> GetDailyLiveCount(global::Atom.Subscription request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncServerStreamingCall(__Method_GetDailyLiveCount, null, options, request);
      }
      /// <summary>
      /// get historical data
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.VehicleCount GetVehicleCount(global::Atom.SearchRange request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVehicleCount(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// get historical data
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The response received from the server.</returns>
      public virtual global::Atom.VehicleCount GetVehicleCount(global::Atom.SearchRange request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVehicleCount, null, options, request);
      }
      /// <summary>
      /// get historical data
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="headers">The initial metadata to send with the call. This parameter is optional.</param>
      /// <param name="deadline">An optional deadline for the call. The call will be cancelled if deadline is hit.</param>
      /// <param name="cancellationToken">An optional token for canceling the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.VehicleCount> GetVehicleCountAsync(global::Atom.SearchRange request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVehicleCountAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      /// <summary>
      /// get historical data
      /// </summary>
      /// <param name="request">The request to send to the server.</param>
      /// <param name="options">The options for the call.</param>
      /// <returns>The call object.</returns>
      public virtual grpc::AsyncUnaryCall<global::Atom.VehicleCount> GetVehicleCountAsync(global::Atom.SearchRange request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVehicleCount, null, options, request);
      }
      public virtual global::Atom.TollVehicleInfo GetVehicleCountSummary(global::Atom.SearchRange request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVehicleCountSummary(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Atom.TollVehicleInfo GetVehicleCountSummary(global::Atom.SearchRange request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_GetVehicleCountSummary, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Atom.TollVehicleInfo> GetVehicleCountSummaryAsync(global::Atom.SearchRange request, grpc::Metadata headers = null, DateTime? deadline = null, CancellationToken cancellationToken = default(CancellationToken))
      {
        return GetVehicleCountSummaryAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Atom.TollVehicleInfo> GetVehicleCountSummaryAsync(global::Atom.SearchRange request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_GetVehicleCountSummary, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override TollAuditServiceClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new TollAuditServiceClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(TollAuditServiceBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Subscribe, serviceImpl.Subscribe)
          .AddMethod(__Method_Unsubscribe, serviceImpl.Unsubscribe)
          .AddMethod(__Method_GetLiveStream, serviceImpl.GetLiveStream)
          .AddMethod(__Method_GetDailyLiveCount, serviceImpl.GetDailyLiveCount)
          .AddMethod(__Method_GetVehicleCount, serviceImpl.GetVehicleCount)
          .AddMethod(__Method_GetVehicleCountSummary, serviceImpl.GetVehicleCountSummary).Build();
    }

  }
}
#endregion
